---
# - name: Creates directory
#   file:
#     path: ~/udapeople
#     state: directory

# - name: Copy artifact archive
#   template:
#     src: "files/ansible-debug.txt"
#     dest: "~/ansible-debug.txt"
- name: Creates directory
  file:
    path: ~/udapeople
    state: directory

- name: Copy index test page
  copy:
    src: "../../artifact.tar.gz"
    dest: ~/udapeople/artifact.tar.gz

- name: Extracting archive
  shell: |
    tar -xf ~/udapeople/artifact.tar.gz -C ~/udapeople


- name: Executing node
  shell: |
    echo $TYPEORM_ENTITIES >> env-test_2.txt
    cd ~/udapeople/
    npm install
    pm2 stop default
    pm2 start npm -- start
